// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookRoute) DeepCopyInto(out *HookRoute) {
	*out = *in
	if in.RouteRef != nil {
		in, out := &in.RouteRef, &out.RouteRef
		*out = new(RouteReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookRoute.
func (in *HookRoute) DeepCopy() *HookRoute {
	if in == nil {
		return nil
	}
	out := new(HookRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repo) DeepCopyInto(out *Repo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repo.
func (in *Repo) DeepCopy() *Repo {
	if in == nil {
		return nil
	}
	out := new(Repo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteReference) DeepCopyInto(out *RouteReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteReference.
func (in *RouteReference) DeepCopy() *RouteReference {
	if in == nil {
		return nil
	}
	out := new(RouteReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSecret) DeepCopyInto(out *WebhookSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSecret.
func (in *WebhookSecret) DeepCopy() *WebhookSecret {
	if in == nil {
		return nil
	}
	out := new(WebhookSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSecretList) DeepCopyInto(out *WebhookSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSecretList.
func (in *WebhookSecretList) DeepCopy() *WebhookSecretList {
	if in == nil {
		return nil
	}
	out := new(WebhookSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSecretRef) DeepCopyInto(out *WebhookSecretRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSecretRef.
func (in *WebhookSecretRef) DeepCopy() *WebhookSecretRef {
	if in == nil {
		return nil
	}
	out := new(WebhookSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSecretSpec) DeepCopyInto(out *WebhookSecretSpec) {
	*out = *in
	out.Repo = in.Repo
	out.AuthSecretRef = in.AuthSecretRef
	out.SecretRef = in.SecretRef
	in.WebhookURL.DeepCopyInto(&out.WebhookURL)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSecretSpec.
func (in *WebhookSecretSpec) DeepCopy() *WebhookSecretSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSecretStatus) DeepCopyInto(out *WebhookSecretStatus) {
	*out = *in
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSecretStatus.
func (in *WebhookSecretStatus) DeepCopy() *WebhookSecretStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookSecretStatus)
	in.DeepCopyInto(out)
	return out
}
